import Head from "next/head";
import { Inter } from "next/font/google";
import AppLayout from "@/components/AppLayout";
import { colors } from "@/styles/theme";
import Button from "@/components/Button";
import GitHub from "@/components/Icons/GitHub";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <section>
          <img src="/logo-twitter.jpeg" alt="Twitter Logo" />
          <h1>Devter</h1>
          <h3>Talk about development with developers</h3>
          <Button>
            <GitHub width={24} height={24} fill={'#fff'}></GitHub>
            Login with github
            </Button>
        </section>
      </AppLayout>
      <style jsx>{`
        h1 {
          color: ${colors.primary};
          margin-block: 15px;
        }
        h3 {
          color: ${colors.secondary};
          width: 70%;
          margin-bottom: 15px;
        }
        section {
          display: grid;
          height: 100vh;
          place-items: center;
          place-content: center;
        }
        img {
          width: 25%;
        }

      `}</style>
    </>
  );
}
